# Generated by Django 4.1.3 on 2022-11-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa', models.IntegerField()),
                ('propietario', models.CharField(max_length=100)),
            ],
        ),
    ]
