# Generated by Django 4.1.3 on 2022-11-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_correspondencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido')], default='PENDIENTE', max_length=20),
        ),
    ]
