# Generated by Django 4.1.3 on 2022-11-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_correspondencia_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondencia',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='destinatario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
