# Generated by Django 4.1.3 on 2022-11-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_correspondencia_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='destinatario',
            field=models.CharField(default='No especificado', max_length=100, null=True),
        ),
    ]
